name: 'Build Image'     #<--- Please change this to your workflow name

on:
  workflow_dispatch: #<--- Run the workflow manually
  push:
    branches:
      - main       #<---- Edit when you want to test

permissions:
      id-token: write
      contents: read
  
jobs:
  docker-build-push-image:
    name: docker-build-and-push-image
    runs-on: ubuntu-latest
    steps:

      - name: 'Azure CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
      - name: 'Build and push image'
        id: build-image
        run: |
           az acr build --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/user-service:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file "Dockerfile" .
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear